import { EvaluationType, ChecklistItem } from './types';

export const CHECKLIST_TEMPLATES: Record<EvaluationType, ChecklistItem[]> = {
  simple: [
    { category: 'Estrutura Visual', item_name: 'Sinais de colisão', status: 'ok' },
    { category: 'Estrutura Visual', item_name: 'Alinhamento de portas', status: 'ok' },
    { category: 'Estrutura Visual', item_name: 'Longarinas aparentes', status: 'ok' },
    { category: 'Estrutura Visual', item_name: 'Colunas', status: 'ok' },
    { category: 'Estética', item_name: 'Pintura', status: 'ok' },
    { category: 'Estética', item_name: 'Vidros', status: 'ok' },
    { category: 'Estética', item_name: 'Faróis', status: 'ok' },
    { category: 'Estética', item_name: 'Pneus', status: 'ok' },
  ],
  complete: [
    { category: 'Estrutura Visual', item_name: 'Sinais de colisão', status: 'ok' },
    { category: 'Estrutura Visual', item_name: 'Alinhamento de portas', status: 'ok' },
    { category: 'Estrutura Visual', item_name: 'Longarinas aparentes', status: 'ok' },
    { category: 'Estrutura Visual', item_name: 'Colunas', status: 'ok' },
    { category: 'Estética', item_name: 'Pintura', status: 'ok' },
    { category: 'Estética', item_name: 'Vidros', status: 'ok' },
    { category: 'Estética', item_name: 'Faróis', status: 'ok' },
    { category: 'Estética', item_name: 'Pneus', status: 'ok' },
    { category: 'Mecânica', item_name: 'Motor (ruído/vazamento)', status: 'ok' },
    { category: 'Mecânica', item_name: 'Câmbio', status: 'ok' },
    { category: 'Mecânica', item_name: 'Suspensão', status: 'ok' },
    { category: 'Mecânica', item_name: 'Freios', status: 'ok' },
    { category: 'Teste de Rodagem', item_name: 'Direção alinhada', status: 'ok' },
    { category: 'Teste de Rodagem', item_name: 'Vibração', status: 'ok' },
    { category: 'Teste de Rodagem', item_name: 'Desempenho', status: 'ok' },
    { category: 'Teste de Rodagem', item_name: 'Ar-condicionado', status: 'ok' },
    { category: 'Documentação', item_name: 'Débitos/Multas', status: 'ok' },
    { category: 'Documentação', item_name: 'Restrição/Alienação', status: 'ok' },
  ],
  premium: [
    { category: 'Estrutura Técnica', item_name: 'Longarina Dianteira Direita', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Longarina Dianteira Esquerda', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Coluna A', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Coluna B', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Coluna C', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Torre de suspensão', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Painel frontal', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Painel traseiro', status: 'original' },
    { category: 'Estrutura Técnica', item_name: 'Caixa de ar', status: 'original' },
    { category: 'Mecânica', item_name: 'Motor (ruído/vazamento)', status: 'ok' },
    { category: 'Mecânica', item_name: 'Câmbio', status: 'ok' },
    { category: 'Mecânica', item_name: 'Suspensão', status: 'ok' },
    { category: 'Mecânica', item_name: 'Freios', status: 'ok' },
    { category: 'Teste Dinâmico', item_name: 'Aceleração', status: 'ok' },
    { category: 'Teste Dinâmico', item_name: 'Frenagem forte', status: 'ok' },
    { category: 'Teste Dinâmico', item_name: 'Ruídos estruturais', status: 'ok' },
    { category: 'Teste Dinâmico', item_name: 'Diagnóstico eletrônico', status: 'ok' },
    { category: 'Histórico', item_name: 'Sinistro', status: 'ok' },
    { category: 'Histórico', item_name: 'Leilão', status: 'ok' },
    { category: 'Histórico', item_name: 'Restrição judicial', status: 'ok' },
    { category: 'Histórico', item_name: 'Recall', status: 'ok' },
  ]
};
